config/routes.rb
Rails.application.routes.draw do
  root to: "toppages#index"
  
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  get "signup", to: "users#new"
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :images
      get :favorites
      get :followings
      get :followers
    end
  end
  
  resources :comments, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true, length: {maximum: 20}
  validates :image, presence: true, length: {maximum: 255}
  
  has_one_attached :image
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :title, presence: true, length: {maximum: 20}
  validates :image, presence: true, length: {maximum: 255}
  
  mount_uploader :image, ImageUploader  
  
  belongs_to :user

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email.downcase!}
  validates :name, presence: true, length: {maximum: 20}
  validates :email, presence: true, length: {maximum: 255},
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: {case_sensitive: false}
  validates :introduction, length: {maximum: 255}
  
  has_secure_password
  
  has_many :comments
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
  
  def following?(other_user)
    self.followings.include?(other_user)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to root_url
    end
  end
  
  def counts(user)
    @count_comments = user.comments.count
    @count_followings = user.followings.count
    @count_followers = user.followers.count
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  

  def show
    @user = User.find_by(params[:id])
    @content = Comment.find(params[:id])
  end
  
  def new
    @comment = Comment.new
  end
  
  def create
    @content = current_user.comments.build(content_params)
    if @content.save
      flash[:success] = "作品を投稿しました"
      redirect_to @content
    else
      @contents = current_user.comments.order(id: :desc).page(params[:page])
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def edit
    @content = Comment.find(params[:id])
  end
  
  def update
    @content = current_user.comment.find(params[:id])
    @content.update(comment_params)
    redirect_to @content
  end
  
  def destroy
    @content.destroy
    flash[:success] = "作品を削除しました"
    redirect_back(fallback_location: new_comment_path)
  end
  
  
  private
  
  def content_params
    params.require(:comment).permit(:content, :image)
  end
  
  def correct_user
    @content = current_user.comments.find_by(id: params[:id])
    unless @content
      redirect_to root_url
    end
  end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :require_user_logged_in
  
  def show
  end

  def new
  end

  def create
  end

  def destroy
  end
  
  
  private
  
  def photo_params
    params.require(:photo).permit(:title, :image)
  end
  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = "フォローしました"
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = "フォローを解除しました"
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = "ログインしました"
      redirect_to @user
    else
      flash.now[:danger] = "ログインに失敗しました"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "ログアウトしました"
    redirect_to root_url
  end
  
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  
  def index
    if logged_in?
      @comments = current_user.comments.order(id: :desc).page(params[:page]).per(3)
      @user = current_user
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :edit, :update, :followings, :followers, :images]
  before_action :correct_user, only: [:edit, :update]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(30)
  end

  def show
    @user = User.find(params[:id])
    @comments = @user.comments.page(params[:page]).per(10)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "ユーザを登録しました"
      redirect_to @user
    else
      flash.now[:danger] = "ユーザの登録に失敗しました"
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "編集を完了しました"
      redirect_to :user
    else
      flash.now[:danger] = "編集に失敗しました"
      render :edit
    end
       
  end
    
    
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page]).per(32)
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page]).per(32)
    counts(@user)
  end
  
  def images
    @user = User.find(params[:id])
    @comments = @user.comments.page(params[:page]).per(10)
    counts(@user)
  end
  
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction)
  end
  
  def correct_user
  @tanin = User.find(params[:id])
    if @tanin != current_user
      redirect_to root_url
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/comments/_comments.html.erb
<ul class="list-unstyled">
  <%= comments.each do |comment| %>
    <div>
      <img src="/assets/take-001.jpg" alt="">
    </div>
  <% end %>
</ul>

app/views/comments/new.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <h1 class="text-center border-bottom mb-5">作品を投稿する</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 offset-sm-2 border">
    
    <%= form_with(model: @comment, local: true) do |f| %>
    
      <div class="form-group mt-4 mb-4">
        <%= f.label :content, "タイトル" %>
        <%= f.text_field :content, class: "form-control" %>
      </div>
      
      <div class="form-group mb-4">
        <%= f.label :image, "画像URL" %><br>
        <%= f.file_field :image, class: "btn btn-secondary col-sm-9" %><span class="col-sm-2 ml-4"><%= f.submit "投稿する", class: "btn btn-primary btn-lg" %></span>
      </div>
      
    <% end %>
    
  </div>
</div>

app/views/comments/show.html.erb
<div>
  <div>
    <%= image_tag(rails_blob_path(@content.image), style: "height: 768px") %>
  </div>
  <div class="media mt-2 border mb-4">
    <img class="rounded-pill mt-2 mb-2 ml-2" src="<%= gravatar_url(@user, {size: 100}) %>" alt="">
    <div class="media-body pl-3">
      <p class="h6 border">UserName: <%= @user.name %> <span class="ml-5 border"><%= @content.created_at %></span></p>
      <p class="h4 font-weight-light pt-3 border-bottom">タイトル : <%= @content.content %></p>
    </div>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <%= model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>  
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Inspiration</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to "ユーザ 一覧", users_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "新規投稿", new_comment_path, class: "nav-link" %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to "My profile", user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "ログアウト", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "新規登録", signup_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Inspiration</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/create.html.erb
<h1>Photos#create</h1>
<p>Find me in app/views/photos/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/new.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <h1 class="text-center border-bottom">作品を投稿する</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    
    <%= form_with(model: @photo, local: true) do |f| %>
    
      <div class="form-group">
        <%= f.label :name, "タイトル" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :image, "画像URL" %>
        <%= f.text_field :image, class: "form-control" %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), local: true, method: :delete) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit "フォロー解除", class: "btn btn-danger btn-sm pl-3 pr-3 mb-2" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit "フォロー", class: "btn btn-primary btn-sm pl-3 pr-3 mb-2" %>
    <% end %>
  <% end %>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <span class="h5 mb-2 ml-5 p-2">最近の投稿</span>
  <p class="border-top mt-3"> </p>
  <div class="container mt-3">
    <div class="row">
      <% @comments.each do |comment| %>
        <div class="col-lg-4">
          <div>
            <%= image_tag(rails_blob_path(comment.image), class: "col-lg-12")%>
          </div>
          <div class="mt-2 ml-3">
            <img class="rounded-pill" src="<%= gravatar_url(@user, {size: 50}) %>" alt="" ><span class="ml-2"><%= link_to comment.content, comment %></span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <p class="border-bottom mt-2"> </p>
<% else %>
<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to the Inspiration</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
</div>
<% end %>

app/views/users/_images.html.erb
<div class="contaier">
  <div class="row">
    <% comments.each do |comment| %>
      <div class="col-lg-6 mb-4">
        <div class="media border">
          <img class="rounded-pill ml-1 mr-1 mt-1" src="<%= gravatar_url(@user, {size: 70}) %>" alt="">
          <div class="media-body border-left">
            <p class="border-bottom text-right mr-2"><%= comment.created_at %></p>
            <p class="ml-2"><%= link_to comment.content, comment %></p>
          </div>
        </div>
        <div>
          <%= image_tag(rails_blob_path(comment.image), class: "col-lg-12 p-0") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_show_users.html.erb
<% if users.any? %>
<div class="card-group">
  <div class="row">
    <% users.each do |user| %>
    <div style="width: 250px;">
      <div class="card mb-4 ml-1 mr-1">
        <div class="text-center">
          <div>
            <img class="mt-3 rounded-circle" src="<%= gravatar_url(user, {size: 100}) %>" alt="">
            <p class="h4 mt-2"><%= link_to user.name, user_path(user) %></p>
          </div>
          <div class="card-body pt-0">
            <div id="user-introduction" class="mt-2" style="height: 95px">
              <p class="border-top m-0"><span>:PRメッセージ</span><%= simple_format(user.introduction) %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
  <%= paginate users %>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
<div class="card-deck">
  <div class="row">
    <% users.each do |user| %>
    <div class="mb-5 col-lg-3">
      <div class="card">
        <div class="text-center">
          <div>
            <img class="mt-3 rounded-circle" src="<%= gravatar_url(user, {size: 100}) %>" alt="">
            <p class="h4"><%= link_to user.name, user_path(user) %></p>
          </div>
          <div class="card-body">
            
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
  <%= paginate users %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3 border border-info">
    <div class="text-center border-bottom border-info mt-4">
      <h1>編集画面</h1>
    </div>
    
    <div class="row">
      <div class="col-sm-10 offset-sm-1">
        
        <%= form_with(model: @user, local: true) do |f| %>
          <%= render "layouts/error_messages", model: f.object %>
          
          <div class="form-group mt-4 mb-4">
            <%= f.label :name, "名前  (Name)" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          
          <div class="form-group mb-4">
            <%= f.label :introduction, "メッセージ" %>
            <%= f.text_area :introduction, class: "form-control" %>
          </div>
          
          <div class="text-center">
            <%= f.submit "編集完了", class: "btn btn-primary rounded-pill p-3 mb-4" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <aside class="col-lg-3">
    <div class="media border">
      <img class="m-2 rounded-circle" src="<%= gravatar_url(@user, {size: 100}) %>" alt="">
      <div class="media-body">
        <div class="h4 font-weight-normal  mt-3 ml-1">
          <span><%= @user.name %></span>
          <p class="h6 mt-2 text-secondary">フォロー : <%= @count_followings %></p>
          <p class="h6 text-secondary">フォロワー : <%= @count_followers %></p>
        </div>
        <%= render "relationships/follow_button", user: @user %>
      </div>
    </div>
    <div id="user-introduction" class="border pt-2 pr-3 pl-3">
      <p class="h6 pt-1 mr-2">:PRメッセージ <span class="ml-4"><%= link_to "編集する", edit_user_path, class: "btn btn-sm btn-primary" %></span></p>
      <p class="border-top"><%= simple_format(@user.introduction) %></p>
    </div>
  </aside>
  <div class="col-lg-9">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= images_user_path(@user) %>" class="nav-link <%= "active" if current_page?(images_user_path(@user)) %>">投稿一覧 <span class="badge badge-secondary"><%= @count_comments %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>">フォロー <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render "show_users", users: @followers %>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <aside class="col-lg-3">
    <div class="media border">
      <img class="m-2 rounded-circle" src="<%= gravatar_url(@user, {size: 100}) %>" alt="">
      <div class="media-body">
        <div class="h4 font-weight-normal  mt-3 ml-1">
          <span><%= @user.name %></span>
          <p class="h6 mt-2 text-secondary">フォロー : <%= @count_followings %></p>
          <p class="h6 text-secondary">フォロワー : <%= @count_followers %></p>
        </div>
        <%= render "relationships/follow_button", user: @user %>
      </div>
    </div>
    <div id="user-introduction" class="border pt-2 pr-3 pl-3">
      <p class="h6 pt-1 mr-2">:PRメッセージ <span class="ml-4"><%= link_to "編集する", edit_user_path, class: "btn btn-sm btn-primary" %></span></p>
      <p class="border-top"><%= simple_format(@user.introduction) %></p>
    </div>
  </aside>
  <div class="col-lg-9">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= images_user_path(@user) %>" class="nav-link <%= "active" if current_page?(images_user_path(@user)) %>">投稿一覧 <span class="badge badge-secondary"><%= @count_comments %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>">フォロー <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render "show_users", users: @followings %>
  </div>
</div>

app/views/users/images.html.erb
<div class="row">
  <aside class="col-lg-3">
    <div class="media border">
      <img class="m-2 rounded-circle" src="<%= gravatar_url(@user, {size: 100}) %>" alt="">
      <div class="media-body">
        <div class="h4 font-weight-normal  mt-3 ml-1">
          <span><%= @user.name %></span>
          <p class="h6 mt-2 text-secondary">フォロー : <%= @count_followings %></p>
          <p class="h6 text-secondary">フォロワー : <%= @count_followers %></p>
        </div>
        <%= render "relationships/follow_button", user: @user %>
      </div>
    </div>
    <div id="user-introduction" class="border pt-2 pr-3 pl-3">
      <p class="h6 pt-1 mr-2">:PRメッセージ <span class="ml-4"><%= link_to "編集する", edit_user_path, class: "btn btn-sm btn-primary" %></span></p>
      <p class="border-top"><%= simple_format(@user.introduction) %></p>
    </div>
  </aside>
  <div class="col-lg-9">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= images_user_path(@user) %>" class="nav-link <%= "active" if current_page?(images_user_path(@user)) %>">投稿一覧 <span class="badge badge-secondary"><%= @count_comments %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>">フォロー <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render "images", comments: @comments %>
  </div>
</div>

app/views/users/index.html.erb
<div>
  <h1 class="border-bottom pb-2 mb-4">ユーザ 一覧</h1>
  <%= render "show_users", users: @users %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-6 offset-sm-3 border border-info">
    <div class="text-center border-bottom border-info mt-4">
      <h1>新規登録</h1>
    </div>
    
    <div class="row">
      <div class="col-sm-10 offset-sm-1">
        
        <%= form_with(model: @user, local: true) do |f| %>
          <%= render "layouts/error_messages", model: f.object %>
          
          <div class="form-group mt-4 mb-4">
            <%= f.label :name, "名前  (Name)" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          
          <div class="form-group mb-4">
            <%= f.label :email, "メールアドレス  (Email)" %>
            <%= f.text_field :email, class: "form-control" %>
          </div>
          
          <div class="form-group mb-4">
            <%= f.label :password, "パスワード  (Password)" %>
            <%= f.password_field :password, class: "form-control" %>
          </div>
          
          <div class="form-group mb-4">
            <%= f.label :password_confirmation, "確認用パスワード  (Confirm)" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
          
          <div class="text-center">
            <%= f.submit "アカウント作成", class: "btn btn-primary rounded-pill p-3 mb-4" %>
          </div>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-lg-3">
    <div class="media border">
      <img class="m-2 rounded-circle" src="<%= gravatar_url(@user, {size: 100}) %>" alt="">
      <div class="media-body">
        <div class="h4 font-weight-normal  mt-3 ml-1">
          <span><%= @user.name %></span>
          <p class="h6 mt-2 text-secondary">フォロー : <%= @count_followings %></p>
          <p class="h6 text-secondary">フォロワー : <%= @count_followers %></p>
        </div>
        <%= render "relationships/follow_button", user: @user %>
      </div>
    </div>
    <div id="user-introduction" class="border pt-2 pr-3 pl-3">
      <p class="h6 pt-1 mr-2">:PRメッセージ <span class="ml-4"><% if current_user == @user %><%= link_to "編集する", edit_user_path, class: "btn btn-sm btn-primary" %><% end %></span></p>
      <p class="border-top"><%= simple_format(@user.introduction) %></p>
    </div>
  </aside>
  <div class="col-lg-9">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= images_user_path(@user) %>" class="nav-link <%= "active" if current_page?(images_user_path(@user)) %>">投稿一覧 <span class="badge badge-secondary"><%= @count_comments %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followings_user_path(@user)) %>">フォロー <span class="badge badge-secondary"><%= @count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link <%= "active" if current_page?(followers_user_path(@user)) %>">フォロワー <span class="badge badge-secondary"><%= @count_followers %></span></a></li>
    </ul>
    <%= render "images", comments: @comments %>
  </div>
</div>